services:
  - type: web
    name: pi-security-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DESTINATION_WALLET
        sync: false
      - key: POLLING_INTERVAL_MS
        sync: false
